import json
import os
import shutil
import math

VERSION = "us" # prob wont support "all" like generate-midis for now
POSSIBLE_VERSIONS = ["eu", "jp", "sh", "us"]

SEQUENCES_DATA_PATH = "sm64/sound/sequences.json"
SEQUENCES_DIR = f"sm64/sound/sequences/{VERSION}/"
SOUND_BANKS_DIR = "sm64/sound/sound_banks/"

EXPORT_DIR = f"export/generate-banks-per-song/{VERSION}/"

def ticks_to_s(ticks:int):
    return ticks * (1000 / 240) / 1000

def vol_normalized(vol:int):
    return vol / 32767

def tuning_to_key(tuning, base_key=60):
    # print(f"tuning {tuning}")
    return round (base_key - 12 * math.log2(tuning))

def handle_ifdef(maybe_dict):
    if isinstance(maybe_dict, dict):
        return maybe_dict['then' if f'VERSION_{VERSION.capitalize()}' in maybe_dict['ifdef'] else 'else']
    else:
        return maybe_dict

def handle_sound(maybe_sound):
    sfx_data = maybe_sound

    if isinstance(sfx_data, dict) and 'ifdef' in sfx_data:
        sfx_data = handle_ifdef(sfx_data)

    if isinstance(sfx_data, dict):
        sfx = sfx_data['sample']
        tuning = sfx_data['tuning']
    else:
        sfx = sfx_data
        tuning = 1

    return {'sfx': sfx, 'tuning': tuning}

def generate_sfzs(song, bank_data):
    os.makedirs(EXPORT_DIR + song, exist_ok=True)
    print(f"\nmaking '{song}'..")


    for k, v in bank_data.items():
        for inst_name, inst_data in v.items():
            sorted_regions = sorted(inst_data, key=lambda x: x['low'])
            final_sfz = "// generated by wizardmantis441 AYO!\n"

            for region in sorted_regions:
                shutil.copy(f'sm64/sound/samples/{k}/{region['sfx']}.aiff', EXPORT_DIR + song + f'/{region['sfx']}.aiff')

                final_sfz += "\n<region>"
                final_sfz += f"\nsample={region['sfx']}.aiff"

                # none of this is useful i think. damn it all
                # if inst_name.startswith('perc'):
                #     # YO ACTUALLY FUCK EVERYTHING AND IM NOT JOKING ALL YALL COMING TO HELL WITH ME
                #     semitones = 12 * math.log2(region['tuning'])
                #     transpose = round(semitones)
                #     cents = round((semitones - transpose) * 100)

                #     final_sfz += f"\npitch_keycenter={region['low']}"
                #     # final_sfz += f"\npitch_keytrack=0"
                #     # final_sfz += f"\ntranspose={transpose}"
                #     final_sfz += f"\ntune={cents}"
                # else:
                final_sfz += f"\npitch_keycenter={tuning_to_key(region['tuning'])}"

                final_sfz += f"\nlokey={region['low']}"
                final_sfz += f"\nhikey={region['high']}"
                final_sfz += f"\nampeg_attack={ticks_to_s(region['envelope'][0][0])}"
                final_sfz += f"\nampeg_vel2attack={vol_normalized(region['envelope'][0][1]) * 100}"
                final_sfz += f"\nampeg_decay={ticks_to_s(region['envelope'][1][0])}"
                final_sfz += f"\nampeg_vel2decay={vol_normalized(region['envelope'][1][1]) * 100}"
                final_sfz += f"\nampeg_sustain={ticks_to_s(region['envelope'][2][0])}"
                final_sfz += f"\nampeg_vel2sustain={vol_normalized(region['envelope'][2][1]) * 100}"
                final_sfz += f"\nampeg_release={ticks_to_s(region['release_rate'])}"
                final_sfz += f"\npan_keycenter={region['pan']}"
                final_sfz += "\n"

            print(f'{inst_name}_{inst_data[0]['sfx']}')
            # print(inst_data)

            with open(EXPORT_DIR + song + f'/{inst_name}_{inst_data[0]['sfx']}.sfz', 'w') as file:
                file.write(final_sfz)

def parse_inst(instrument_data, bank):
    ranges = []

    if 'normal_range_lo' in instrument_data:
        sfx_data = handle_sound(instrument_data['sound_lo'])
        ranges.append({
            'low': 0,
            'high': instrument_data['normal_range_lo'],
            'sfx': sfx_data['sfx'],
            'pan': 60,
            'tuning': sfx_data['tuning'],
            'release_rate': instrument_data['release_rate'],
            'envelope': bank['envelopes'][instrument_data['envelope']]
        })

    sfx_data = handle_sound(instrument_data['sound'])
    ranges.append({
        'low': (instrument_data['normal_range_lo'] + 1) if 'normal_range_lo' in instrument_data else 0,
        'high': (instrument_data['normal_range_hi'] - 1) if 'normal_range_hi' in instrument_data else 127,
        'sfx': sfx_data['sfx'],
        'pan': 60,
        'tuning': sfx_data['tuning'],
        'release_rate': instrument_data['release_rate'],
        'envelope': bank['envelopes'][instrument_data['envelope']]
    })

    if 'normal_range_hi' in instrument_data:
        sfx_data = handle_sound(instrument_data['sound_hi'])
        ranges.append({
            'low': instrument_data['normal_range_hi'],
            'high': 127,
            'sfx': sfx_data['sfx'],
            'pan': 60,
            'tuning': sfx_data['tuning'],
            'release_rate': instrument_data['release_rate'],
            'envelope': bank['envelopes'][instrument_data['envelope']]
        })

    return ranges

def parse_perc(percussion_data, bank):
    ranges = []

    for i, key in enumerate(percussion_data):
        sfx_data = key['sound']
        if isinstance(sfx_data, dict):
            sfx = sfx_data['sample']
            tuning = sfx_data['tuning']
        else:
            sfx = sfx_data
            tuning = 1

        ranges.append({
            'low': i,
            'high': i,
            'sfx': sfx,
            'pan': key['pan'],
            'tuning': tuning,
            'release_rate': key['release_rate'],
            'envelope': bank['envelopes'][key['envelope']]
        })

    return ranges

def generate_banks(song, banks):
    total_bank_data = {}

    for b in banks:
        with open(SOUND_BANKS_DIR + b + '.json', 'r') as file:
            bank = json.load(file)

            sample_bank = handle_ifdef(bank['sample_bank'])

            instruments = {}
            for k, v in bank['instruments'].items():
                if k.startswith('inst'):
                    instruments[k] = parse_inst(v, bank)
                elif k.startswith('perc'):
                    instruments[k] = parse_perc(v, bank)
                else:
                    print('not an inst or percussion? what the fuck are you')

            total_bank_data[sample_bank] = instruments # TODO fix 00_sound_player overriding itself

    generate_sfzs(song, total_bank_data)

def main():
    with open(SEQUENCES_DATA_PATH, 'r') as file:
        banks_data = json.load(file)

        for k, v in banks_data.items():
            banks = v
            if k == "comment": continue
            if k == "22_cutscene_lakitu": banks = v['banks']

            generate_banks(k, banks)

if __name__ == "__main__":
    main()